openapi: 3.0.4
info:
  title: Spark API V2
  version: 2.0.0
servers:
  - url: http://localhost:8080/v2
paths:
  /health:
    get:
      summary: ヘルスチェック
      operationId: health
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello Echo!"
