// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package v1

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// AuthLoginJSONBody defines parameters for AuthLogin.
type AuthLoginJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Password string              `json:"password"`
}

// AuthRefreshParams defines parameters for AuthRefresh.
type AuthRefreshParams struct {
	Authorization string `json:"Authorization"`
}

// AuthRegisterSendOtpJSONBody defines parameters for AuthRegisterSendOtp.
type AuthRegisterSendOtpJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// AuthRegisterVerifyOtpJSONBody defines parameters for AuthRegisterVerifyOtp.
type AuthRegisterVerifyOtpJSONBody struct {
	Otp string `json:"otp"`
}

// AuthLoginJSONRequestBody defines body for AuthLogin for application/json ContentType.
type AuthLoginJSONRequestBody AuthLoginJSONBody

// AuthRegisterSendOtpJSONRequestBody defines body for AuthRegisterSendOtp for application/json ContentType.
type AuthRegisterSendOtpJSONRequestBody AuthRegisterSendOtpJSONBody

// AuthRegisterVerifyOtpJSONRequestBody defines body for AuthRegisterVerifyOtp for application/json ContentType.
type AuthRegisterVerifyOtpJSONRequestBody AuthRegisterVerifyOtpJSONBody
